[project]
name = 'parti-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.YieldPoint-System]
path = 'contracts/YieldPoint-System.clar'
[contracts.contribution-tracking]
path = 'contracts/contribution-tracking.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
