[project]
name = 'parti-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.YieldPoint-System]
path = 'contracts/YieldPoint-System.clar'
clarity_version = 1
epoch = 2.05

[contracts.contribution-tracking]
path = 'contracts/contribution-tracking.clar'
clarity_version = 3
epoch = 3.0

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 3
epoch = 3.0

[contracts.retroactive-rewards]
path = 'contracts/retroactive-rewards.clar'
clarity_version = 3
epoch = 3.0

[contracts.staking-slashing]
path = 'contracts/staking-slashing.clar'
clarity_version = 3
epoch = 3.0

[contracts.voting-power-calcu]
path = 'contracts/voting-power-calcu.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
